name: PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Build Docker image
        uses: docker/build-push-action@v2.5.0
        with:
          push: false
          tags: durandj/kopia:latest
          build-args: |
            KOPIA_VERSION=0.7.3
