name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build and Release Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Build Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          tags: |
            durandj/kopia:latest
            durandj/kopia:0.7.3
          build-args: |
            KOPIA_VERSION=0.7.3
